# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(max_length=2000, unique=True, verbose_name='Full Url')),
                ('short_url', models.CharField(max_length=6, unique=True, verbose_name='Short Url')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Visit Count')),
            ],
            options={
                'verbose_name_plural': 'Short Urls',
                'verbose_name': 'Short Url',
                'ordering': ['-date_created', 'visit_count'],
            },
        ),
    ]
